### ISSUE TITLE
Seems like current Travis CI setup fails to install

### ISSUE THREAD

**Issue by honzajavorek** [ungrim97/Dredd-Hooks#3]
Would you please try whether current master really passes? I checked out this repo for our integration tests and it seems to fail to install now: https://travis-ci.org/apiaryio/dredd/builds/151557303

Everything was fine couple of days ago. Maybe they changed some default settings in Travis?

```
The program 'cpanm' is currently not installed. To run 'cpanm' please ask your administrator to install the package 'cpanminus'
The command "eval cpanm --quiet --installdeps --notest ." failed. Retrying, 2 of 3.
The program 'cpanm' is currently not installed. To run 'cpanm' please ask your administrator to install the package 'cpanminus'
The command "eval cpanm --quiet --installdeps --notest ." failed. Retrying, 3 of 3.
The program 'cpanm' is currently not installed. To run 'cpanm' please ask your administrator to install the package 'cpanminus'
The command "eval cpanm --quiet --installdeps --notest ." failed 3 times.
The command "cpanm --quiet --installdeps --notest ." failed and exited with 127 during .
```

**Comment by ungrim97** [comment]
The perl build is working fine for me currently (though with some sporadic fails). https://travis-ci.org/ungrim97/Dredd-Hooks/builds/151767491

Does #4 fix the issue for you?

**Comment by ungrim97** [comment]
I am not massively familiar with TravisCI so am not entirely sure what is happening

**Comment by honzajavorek** [comment]
Yes, #4 fixes it.
